Squashed 'Vendor/container/' changes from ae5572dbb..293233996
293233996 Fix transparent erase signature to "K&&"
73d91c52c Implement transparent insert_or_assign (C++26) for map.
c7a3d8620 Fix incorrect return value description for insert_or_assign with hint.
d9404f6d3 Increase timeout value
3fec38d9c Fix -Wcast-qual
5923493b1 Fix -Wsign-conversion
1ef175aa9 Fix -Wcast-qual warnings.
7ba8bae1b Update changelog with #254
22bc5024d Implement erase_if for map and flat_map
a7873e975 Add erase_if for set/flat_set
5fea20089 Correct indentation for erase/erase_if
a9f301bbb Add erase_if testing for vector and list
6911e6adc Implement erase/erase_if for list and slist
ec6364a3c Fix inserter function, it was inserting in reverse order
3763c80ec Added C++20 remove and remove_if overloads to vector-like containers
4f6c915f9 Add minimal instantiation to pmr compilation tests
8b6bd5905 Fixes #321 ("devector does not work with pmr allocators")
247ffd033 Fixes #304 ("Usage of boost::container::small_vector with custom allocator")
2170155cb Fixes #312
1abb69871 Update chagenlog with #293
0db85fbb7 Use operator_new_allocate/operator_delete_deallocate for test allocators
cae7d2c30 Add missing <boost/container/throw_exception.hpp> include
e18078f84 Define operator_new_allocate/operator_delete_deallocate helpers, taking care of __cpp_aligned_new and __cpp_sized_deallocation, and use them in new_allocator
ef4626b53 Forward declare std::align_val_t
bdad103aa Add missing include for true/false_type
243b74cb9 - Refactor "prot_reallocate_map_and_nodes" "priv_reserve_elements_at_back" and "priv_reserve_elements_at_front" - Use 1,5 growth factor for reservable deques
a4ae4a219 Add "stored_size" to the custom deque example
ad69850bb Add "stored_size" option to the "Configurable deques" chapter
0a2144896 Fix Options documentation issue with Doxygen
2774b3c9b Remove "ingroup" from doxygen documentation
5019f5c12 Change index organization to simplify it
e68a3ac4d Add reservable deque to benchmark
806aee2b7 Add experimental "reservable" option to deque.
7115c0ae9 Fix incorrect ifdef for GCC pop_options
d1e26b23f Make front/back_capacity public
990e2b884 Add front_capacity and back_capacity
8fc53b472 Add default block size test
8470abf32 Comment default block size logic, round up default_block_start
df4af0989 Implement the initial machinery to support "stored_size" option.
679ace9b8 Correct ">>" disambiguation for C++03
a05500c3a Add construction from input_iterator
473bff0c5 Make default block bytes dependent on the architecture's word-width
ea0af71ac Add allocator converting constructor +  default constructor
85ea77309 Put range check in the first position to clean up code
1519d4813 Make small_size_type_allocator a template so that it can be rebinded
08d1a1794 Rename CustomAllocator to small_size_type_allocator and move it to a common header so that other classes can use it
5536aa59e Add test to check that a correctly "stored_size_type"-enabled vector is smaller than the original
3ebb0662d Add deque_iterator explicit instantiation.
d877b3662 Make deque_iterator explicit instantiation friendly.
8bd7ebdd7 Add details about deque's new implementation
c59f740c6 Put deque_iterator in the main namespace, like in vector
c006897da Try workaround for GCC 12 C++03 failures
5be25a65d Add new deque implementation.
7495c1526 Remove old test/bench files
8834ab088 Use selective BOOST_CONTAINER_FORCEINLINE on simple forwarding functions
e7d5add69 Merge pull request #319 from m4xG4/static_vector_clear_doc
900b58a26 added missing dots
3ad96419a fixed complexity documentation for static_vector clear
6be91b833 Update changelog with #248
814efb53d Remove redundant "value" in is_trivially_copy_assignable for std::pair
9552828c5 Apply optimization traits also to std::pair
7dbf9a1b0 Reinterpret_cast to void to silence potential warnings
38c55cac0 Add 100% growth factor vector
77fb53dbf Add new_deque and its test
c9a4b78d4 Update changelog with 317
0e845ae84 Update gitignore with experimental new_deque
1f043d03b Merge pull request #317 from nigels-com/revert-issue-209
68fa75231 Merge branch 'develop' into revert-issue-209
08ded3247 Increase range size to 8 and template the integer type to contemplate both trivial and non-trivial types.
c982fe598 Add some new erase tests
42d7f18d4 Forceinline some very trivial functions.
29c24520e Merge pull request #313 from nigels-com/cmake-test
bcacd264e Merge pull request #315 from nigels-com/readme-travis-status
ada5ee307 Merge branch 'develop' of github.com:boostorg/container into develop
9ad078f9b Add new algos and simplify template parameters
f0708dedc Merge pull request #314 from nigels-com/resolve-clang-19-warnings
d618e482a Merge pull request #316 from nigels-com/ifdef__cpp_sized_deallocation
3e07b0d4d Merge pull request #318 from nigels-com/whitespace-fixup
bdce6c01f Minor whitespace tidy-up
a165f4919 Partial revert of changes for Issue #209 - compiler warnings
f0b0dacf2 __cpp_sized_deallocation is not always defined (clang is opt-in) for Issue #306
6cd7f1623 README: Remove stale links to Travis build status
f6fdd0945 Resolve clang-19 warnings for Issue #300 - pointer to non-trivially copyable type
8a47e6e33 cmake support for building and running tests
7972bb2c9 Fixes #305: ("Warnings with -Wstrict-prototypes").
db5b2f8a3 Add #294 to release notes
98834ad36 Merge pull request #294 from zjyhjqs/feat/header-only-option
a89742f65 Merge pull request #311 from Flamefire/test-link-update
862ae3673 Fixes #310 ("flat_map: Mention correct type in documentation of emplace and emplace_hint"
83b4420a2 Update Link to regression test matrix in README
341cda240 Add option to use header-only `Boost::container`
96653536f Fixes #309 ("Performance regression of boost::container::static_vector introduced in boost v1.86")
52ad24fe0 Add GitHub #307 to release notes
b6a2a6ba6 Merge pull request #307 from TheJCAB/fix-MSVC-C4146-warnings
456e20e41 Ignore new experimental new_deque implementation
74c06d3a5 Protect iwth BOOST_CXX_VERSION >= 201103L as Boost.Iterator does not support C++03
18f29c6ed Fix all instances of MSVC warning C4146 (unsigned negation)
e680bd79a Fix class invariant comment. In this implementation default constructed deque make no allocation so in that case start and finish are singular iterators.
ba82a1da7 Use windows 2025 runner
8ca003cab Remove Windows 2019 as it's not longer supported in github
e8baf848b Fixes #250 ("Custom container leads to "invalid use of incomplete type" for "struct boost::container::dtl::container_rebind"")
aa4b21568 Add clang-19 toolset
b13c1fe8a Avoid C++03 testing in clang/libc++
d12528d97 Disable "-Wdeprecated-declarations" for max_size which was deprecated in the standard.
bae5554f5 Use SFINAE to avoid errors in C++03 mode and std::pair
ae221a13f Fix GCC compiler versions
fad402d03 Fixes #234 ("dlmalloc_ext_2_8_6.c:warning: iteration 2305843009213693951 invokes undefined behavior")
a6a41e235 FIxes #297 ("flat_map::try_emplace does not compile if allocator has construct")
1f543216d Disable Wdeprecated-declarations when using deprecated allocator
65dc4d1ac Use static_assert instead of runtime checks for "has_trivial_destructor_after_move"
b42189922 Remove deprecated macos-12 and add macos-15
866fd30df Update changelog with bug 296
3e70ecfa8 Avoid comparing iterators that could have been invalidated after erase()
a0848ceaf Fixes #295 ("Bug in small_vector::swap")
83b8d5748 Use #<boost/move/detail/std_ns_begin/end.hpp> before using BOOST_MOVE_STD_NS_BEG
608bcb45a Merge pull request #291 from Lastique/patch-1
fc81064ee Improve description of stored_size
af58c7d22 Added `stored_size` option to `small_vector`
13603d7de Added `stored_size` option to `static_vector`
c4cfad740 Disable unreachable code warning for MSVC
27e5a5dc8 Update changelog with 261 and reorder issues fixed in Boost 1.86.
78d1a30e6 Fixes #261 ('"End iterators are not dereferencable")
0a62c979a Use boost::hash instead of boost::hash_value (properly tests #290 use case)
bf029b6a5 - Adds compatibility tests between string and std::string_view - Fixes #290 ("boost::hash<container::string> doesn't match boost::hash<std::string_view>")
18a86594b Fix some Wshadow warnings for old GCCs
4cc14fc42 Propagate the potentially "void" allocator to the underlying vector to shorten symbol name lengths.
49440c352 Add compile-time check to make sure allocator_type::value_type and container's value_type are the same type.
5bdca12ac Merge branch 'develop' of github.com:boostorg/container into develop
84e852f63 Fix GCC comparison for flat_map tests
f2fb40fe9 Merge branch 'develop' of github.com:boostorg/container into develop
12afa8457 Disable std::vector as underlying sequence in old GCCs as we have compilation errors due to unsupported features.
13180fd60 Disable std::vector as underlying sequence in old GCCs as we have compilation errors due to unsupported features.
e9db423fb Update changelog for 1.87
72a6b1e00 Fixes #288 ("Compile error when using flat_map::extract_sequence with small_vector")
daa81ed5b Expand flat_map testing coverage
c552a23d9 Use BOOST_CXX_VERSION instead of __cplusplus
d26e35d46 Fix typos, unneded empty lines
69136f996 Optimize merge and sort with the utility unused_storage
bd8c8b032 Add unused_storage optimization function
48acf451b Fix incorrect invariant check for iterators. We don't have a proper comparator for them, we need to wait until they are inserted in the sequence before checking invariants.
ceadad2e6 Avoid rebinding the allocator o container if std::pair is movable (impl_pairt_ is the same type as std_pair_t)
419b1e9f0 Fix merge[_unique] handling of input iterators. It was not handled at compile time, leading to compilation errors.
6c735211f Ignore Bin folder
19a2f5ea9 Fix WConversion warning for DetectMember_*
74dfab45f Fix warning "incompatible pointer types passing 'int *' to parameter of type 'volatile long *' [-Wincompatible-pointer-types]", in clang-win
2d1348930 Merge branch 'develop' of github.com:boostorg/container into develop
c029dc3cd Merge pull request #287 from grafikrobot/modular
3876e1158 Add "bench" to the global test suite
df9132c80 Update build dependencies.
4b56fdee8 Sync from upstream.
25437bea4 Fix doc include path refs.
96ae757e6 Adjust doc build to avoid boost-root references.
0f448277c Remove hash_value from string, Boost.ContainerHash hashes containers by default now.
11781732c Sync from upstream.
e08a06489 Remove prj from index
2ded200bd Move inter-lib dependencies to a project variable and into the build targets.
44e5d5740 Update copyright dates.
fbf07feea Change all <source> references to <library>.
bc554a9ee Sync from upstream.
4ea9c6431 Use algo_equal to reduce test dependencies
8d0dc6dae Fixes #285 ("devector<>::push_front asserts after clear()")
0abc02729 Sync from upstream.
3ed1c76ef Remove C++03 for clang/libc++
ebf698f8a Adjust BOOST_CONTAINER_GCC_COMPATIBLE_HAS_DIAGNOSTIC_IGNORED since clang claims to be GCC 4.2 but supports this feature.
849f61275 Add gcc -14 and clang-18
bdc734f1e Avoid noisy warnings when instantiating BOOST_INTRUSIVE_HAS_MEMBER_FUNCTION_CALLABLE_WITH
7d8040704 macos-11 was deprecated/removed as GitHub-hosted macOS runner, use macos-14 instead.
9ebdbb8ab Try the same approach as Boost.Core with snapshots
e0dd257c9 Remove deprecated actions/checkout@v3
df03ffc8e Fixes #241: flat_map should support same interface as std::map
07675d6c5 Sync from upstream.
6f10e5288 Update changelog with #259
cb9b66723 Sync from upstream.
2a2c8bd47 Bump B2 require to 5.2
402528892 Update changelog with #266 and #245
a070ce232 Fixes #245 ("flat_tree::insert ordered range doesn't assert sorting")
2d097fe45 Roll back and use dtl::value_init to maximize compatibility between std versions
43ac22eff Add test for move assignable index operator
f21c5fb72 Add missing detail/pair.hpp include
d1d8c43c2 Add detail/pair header
acd4f41ed Remove unneeded header
7c9fb0d76 Include pair.hpp since dtl::pair is used
a331d3387 Include detail/is_pair.hpp since forward declares boost::tuples::tuple
730ceb753 Sync from upstream.
a4c4c3b31 Define and use BOOST_CONTAINER_CONSTANT_VAR to support BOOST_INLINE_CONSTEXPR and static const global variables.
33d28a12d Don't use C++03 in Macos regression tests
0977e6b1d Use BOOST_STATIC_CONSTEXPR where applicable
8217bc03b Update changelog for Boost 1.86
13be16a0c Don't use default-constructed KeyNodeCompare to support stateful comparison objects
24c978b55 Clarify clear() does not alter capacith()
e62694f5f Sync from upstream.
aa35950ca Add shrink_to_fit tests to small_vector
dad179ddf Fix incorrect memory free order in prot_shrink_to_fit_small, fixing a potential memory leak
c7702d20e Reformat small inline functions
aa473160d Remove unused make_unique.hpp
5f43b093c Sync from upstream.
9da5dc49f Refactor move constructor and swap implementations for small_vector as in some cass unnecesary heap allocation was performed. Add tests for this.
414205004 Disable Wstringop-xxx false positives also in newer GCCs
7ec7de921 Remove unused or unneeded _id member
0219333fa Disable strict aliasing for C++03 implementations as type-punning is used to make value_type movable.
af24268fb Sync from upstream.
f46ee4391 Protect struct POD definition with the same macro as the test
2f0155224 Disable Wstringop-overflow also in GCC 11
2ed37446b Update changelog with #273 and #269
918372911 Update changelog with #277 and #280
c9feaa658 Merge pull request #277 from Neumann-A/patch-1
397fbda8b Fixes #280 ("Several containers don't support non-movable types when move assigning")
c38fe90e9 Reduce iterations for resgresion tests
c09c9b580 Avoid using transform iterator as null pointer dereferences might happen
8d1797874 Document block_size option in deque_options
292bab35c Revert accidental commit
59d760c08 Document block_size option in deque_options.
750033d8c Remove dep on boost::static_assert
1d65663bc Add requires-b2 check to top-level build file.
27b633c63 Sync from upstream.
894c5c14c Add missing NO_LIB usage requirements.
20ad12f20 Remove UB in flat_map implementation when the implementation has a movable std::pair
31752171c Add missing b2 testing module import.
9fea4700c Sync from upstream.
429024ca4 Add experimental (macro protected) support for lighter iterators
03abe8c02 Return start() pointer by value to limit aliasing
978bbb113 Clean force_ptr usage and use launder_cast
56cc38f76 Update test_iterator_random test for vector-like containers
efdf26e32 Update dependencies.
25d0349ad Switch to library requirements instead of source. As source puts extra source in install targets.
c9e544df8 Fix typos and bad link
51bee1abb Sync from upstream.
6291e6c1b Update quickbook version to 1.7 and fix detected errors in qbk
1c17646cd Make the library modular usable.
6e697d796 Rewrite default_init_test() to make harder for the compiler to optimize because we rely on UB to test memory was not initialized.
3c8c087eb Change internal_storage() implementation to avoid UBSan errors when N is zero.
fb822f043 Update 1.85 changelog
514e88b37 Remove unneeded header
7c74232a4 Remove Boost.StaticAsser dependency
716ec4886 Add new toolsets and fix clang+libstdc++ incompatibility in Ubuntu 22.04
b14e7cedb libc++ up to version 14 does not support span deduction guides
b8b089730 Disable test for clang with libstdc++ as clang triggers an error parsing STL headers with concepts (stl_iterator.h: error: requires clause differs in template redeclaration")
e99536c53 Remove unused variable
eda6b8dd8 Correct testcase that was failing in GCC-12
fa14c4763 Reduce additional BOOST_CONTAINER_FORCEINLINE uses
4fcd7aea6 Workarounds to GCC-12 false positive warning
1a4a205ea Don't use BOOST_CONTAINER_FORCEINLINE extensively, due to potential code bloat
9c852071f Update github regression tests with more platforms and performance improvements
546ee5c06 Fixes #243 ("rebind makes build fail in boost::small_vector with libstdc++-13 and later ")
52013a99e Fixes #225 ("variable set but not used in dlmalloc_ext_2_8_6.c")
3ba7237b3 Update changelog with #242
8ae15965e Fixes #242 ("Issue with string::rfind")
51f6cf69f Disable forceinline for clang compilers, see https://lists.boost.org/boost-users/2023/04/91445.php and https://github.com/llvm/llvm-project/issues/62202
22357b34b Update changelog with #233
5cc961748 Fixes #233 ("Can't std::move small_vector with move-only type")
db96d2ad4 Fixes #240 ("_GLIBCXX_DEBUG detects issues in flat_set/map")
5cea4e871 Fixes #236 ("flat_tree::erase_unique uses wrong iterator")
8ec0bda4b Fixes #237 ("there is no warning number /4675/4284/4345")
3ef88e47b Update changelog with issue #238 ("Containers should not be using memset to value-initialize POD types")
81fd39457 Merge pull request #239 from dangelog/issue238
58904e3f2 Add CMakeLists.txt to the project
b694ada29 Do not memset(0) POD types
acc5b088f Update CMakeLists.txt with new dependencies
552688c7f Simplify dependencies dropping Boost.Core
70f756960 Update hash bench projects
9e3b3295e Add _CRT_SECURE_NO_WARNINGS
b3fd98510 Boost.Config is not needed
43a9e87d2 Remove unneeded project
0aa832cf1 Disable "-Warray-bounds" for GCC12 due to false positives
5e31afe60 Remove unneeded file
af381d82a Avoid dependency on boost::ignore_unused
cfa3dda60 Add BOOST_CONTAINER_FORCEINLINE to trivial functions
2e7983f99 Add missing boost/assert or static_assert include
4e474cbd0 Remove experimental hash_xxx forward declarations
2b8e3cfaf aligned_storage is no longer used in the implementation, so remove the header include.
855ff7707 Use "unsigned long long" for wchar_t sprintf_number algorithm to avoid warnings in Win64
efde61999 Use remove_const to correctly extract key_type from value_type, as the typical case is pair<const KeyType, MappedType>
d9ecdd8f6 Add BOOST_CONTAINER_FORCEINLINE in trivial functions
2f70cddf5 Update changelog with #232
f5df1cc5c Remove unmaintained travis file
3872eaa9d Merge pull request #228 from strager/fix-dox
e9b09a5ee Use direct-initialization since copy-initialization invokes the copy ctor in older standard versions
5e76b844a Merge pull request #232 from georgthegreat/patch-1
ef3c4f41c Merge pull request #235 from lrineau/patch-1
d7b877f92 Fix a doc typo in flat_set.hpp
488500ed8 Fix using pmr::polymorphic_allocator in pre-main
cae4b7cbc Fix typo in memory_resource docs

git-subtree-dir: Vendor/container
git-subtree-split: 29323399657194e8968656ab85b47139ca722ec2