Squashed 'Vendor/move/' changes from 0a1cb78c9..754ef1f5b
754ef1f5b Increase timeout
b9ea61c1c Fix "1059: error: Mismatched [endsect] near column 9"
50e7fdbc1 Update changelog with #61
f0dbbd60e Merge pull request #62 from Flamefire/patch-1
742138d88 Avoid warning in `launder_cast`
1d398dddc Make iterator_to_pointer for raw pointers forceinline
23f935631 Merge pull request #60 from sdarwin/boost-ci
aa7423cbf Use windows 2025 runner
a8b8cfd3c Remove Windows 2019 as it's not longer supported in github
a58e71e5d Set CI B2_CI_VERSION=0
40d2be68b Add clang-19 toolset
e9ff3ca09 Fix #59 again (missing BOOST_MOVE_STD_NS_END closing brace)
5f073f8f0 FIxes #59 ("std_ns_begin.hpp: missing definition of BOOST_MOVE_STD_NS_BEG")
51a4762fd Avoid C++03 testing in clang/libc++
e343c5301 Add #58 in 1.88 changelog
b027b84fe Merge pull request #58 from stbergmann/c++26-vararg-comma
aa25af192 Avoid -Wdeprecated-variadic-comma-omission with GCC 15 trunk -std=c++26
a2bb5c885 Update changelog with #57
634ca276e Remove deprecated macos-12 and add macos-15
b7a04d320 Use new <__utility/swap.h> header for modern libc++ versions. Fixes #57
5fe1c7a43 Fix #56: ("Forward declarations of std types cause compilation errors on some platforms").
18b0f7e18 Fixes #56 ("Forward declarations of std types cause compilation errors on some platforms")
7398ab9ba Fixes #292 ("Forward declarations of std types cause compilation errors on some platforms")
974dc35b6 Add move_core test to make sure movable classes can be defined with the minimal header.
0d7bc2eaf Simplify core.hpp using "meta_utils_core.hpp" instead of "meta_utils.hpp"
7430e9233 Remove unneeded includes
9f33e1acb Avoid unneeded includes
e5d2f7666 Add missing >cstddef>
dfb590207 Merge pull request #55 from jschueller/patch-1
bb124ff9b Add BOOST_MOVE_FORCEINLINE for conversion operators.
164e070cb Lowercase windows.h
55b5a3ece Merge branch 'grafikrobot-modular' into develop
6cd43ef45 Adjust doc build to avoid boost-root references.
36c5a8185 Move inter-lib dependencies to a project variable and into the build targets.
b36aa5816 Update copyright dates.
a208d101f Change all <source> references to <library>.
06a4b9c5a Sync from upstream.
70c57e804 Add latest gcc/clang/macos versions
a56cce87b Sync from upstream.
c973467a3 Avoid C++03 in MacOS
ff0cffb95 Bump B2 require to 5.2
b4bb259ac Add requires-b2 check to top-level build file.
e831be29f Sync from upstream.
d0631eec7 Implement aligned_struct with __declspec(align(x)) for x = 8 as MSVC will not align the stack if a built-in type is used (like double).
d6b970285 Add launcer helper
d2e6c80e2 Switch to library requirements instead of source. As source puts extra source in install targets.
56b2d7936 Sync from upstream.
08f16be93 Fix syntax error detected in quickbook 1.7
d34122e8d Update quickbook language to 1.7
05d00ac95 Make the library modular usable.
6b81611b9 Fixes #51: ("Compiler deprecation warnings with VS2019 Version 16.10 and boost/move headers")
bfe39f279 Add timeout to tests
c5fcde792 - Update gitignore with local msvc projects and binaries
7c0107262 Fix typo in BOOST_MOVE_STATIC_ASSERT
4798a80e5 - Remove clang with listdc++ tests in C++2b mode as there is an incompatibility between them. - Add new toolsets present in ubuntu 23.04. - Use container images also for Ubuntu 22.04
51753c243 Add apt-get dist-upgrade to actions.
11930bbf5 - Add is_unsigned trait - Add make_unsigned for 128 bit integers - Fix is_scalar traits
60f782350 Reduce clang-win tests to 64 bit as the regression timeouts because clang compilation is much heavier than msvc.
47008b007 Avoid GCC 4.4, too old to support, even in C+03 [skip ci]
e7f403c78 Add more windows toolsets from Boost.Core's CI
97b08b067 Use Boost.Core's configuration for CI as it supports a wide range of platforms
2709deb82 Test multilib for gcc-9
aa6f622ab Revert "Add old compilers using containers, gcc multilib, multiple clang versions"
e73ea9655 Add old compilers using containers, gcc multilib, multiple clang versions
879c17540 Remove Ubuntu 18 runners. Use number of processor for parallel execution
e7489078d - Use assertions and invariant checking in release mode testing for sorting/merging - Disable Wconversion due to iterators using small "difference_type" integers.
b6b8414cf Minimize BOOST_MOVE_FORCEINLINE
cc618e1ba Fixes #50 (Disabling forceinline with Clang broke the build)
a6cdf134d Disable forceinline with Clang, see https://github.com/llvm/llvm-project/issues/62202
f1fbb4513 Use [[msvc::intrinsic] attribute if available in move/forward in order to improve debug experience
0865eb3a8 Use lightweight test instead of assert
2513f1bdc QueryPerformanceXXX does not fail after WindowsXP, simplify code.
99294523d Update CMakeLists.txt to reflect actual dependencies.
bbd3a99dc Avoid std::size_t since no <cstddef> include is present
9cbef2df9 Reduce Boost.Move dependencies to only Boost.Config
d1bd02f05 Avoid <boost/core/no_exception_support.hpp> to simplify dependencies for the library
12c1a6aaf - Update CMakeLists with missing dependencies - Update README and erase unused build tests
b33190fba Avoid dependency on Boost.Core only due to "ignore_unused"

git-subtree-dir: Vendor/move
git-subtree-split: 754ef1f5ba347603cd2edd2d4659bc7bf978ff31